version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17

    steps:
      - checkout
      # Restore cache for Docker build
      - restore_cache:
          keys:
            - docker-cache-{{ .Branch }}-{{ checksum "Dockerfile" }}
      # Install Docker
      - setup_remote_docker

      # Build Docker image
      - run:
          name: Build Docker Image
          command: |
            docker build -t test_image .
            
      # Push Docker image to a registry (e.g., Docker Hub)
      - run:
          name: Push Docker Image
          command: |
            source .env 
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push "$DOCKER_USERNAME/test_image"

      # Save cache for Docker build
      - save_cache:
          key: docker-cache-{{ .Branch }}-{{ checksum "Dockerfile" }}
          paths:
            - /var/lib/docker

      # Run Docker container and capture the container ID
      - run:
          name: Run Docker Container
          command: |
            CONTAINER_ID=$(docker run -d -p 5000:5000 "kt2505/test_image")
            echo "Container started with ID: $CONTAINER_ID"
            if docker inspect --format '{{.State.Running}}' $CONTAINER_ID &> /dev/null; then
              echo "Container is already running."
            else
              echo "Container is not running. Starting...$CONTAINER_ID"
              docker start $CONTAINER_ID
            fi

  docker_container_ip:
    docker:
      - image: circleci/node:14.17

    steps:
      - checkout

      # Install Docker
      - setup_remote_docker

      # Output container IP
      - run:
          name: Show Container IP
          command: |
            CONTAINER_IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' $(docker ps -q))
            echo "Server is running at http://$CONTAINER_IP:5000"

workflows:
  version: 2
  build:
    jobs:
      - build
      # Run docker_container_ip job after build job succeeds
      - docker_container_ip:
          requires:
            - build
