version: 2.1
jobs:
  first_job:
   docker:
      - image: circleci/node:14.17
   steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Npm Lib
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  build:
    jobs:
      - first_job          
