version: 2.1
jobs:
  run_project:
    docker:
      - image: kt2505/my-node-image:latest
    steps:
      - checkout
      - run:
          name: Check Docker
          command: docker --version || echo "Docker not found"
      - run:
          name: Install Docker client
          command: |
            if ! command -v docker &> /dev/null; then
              curl -fsSL https://get.docker.com | sh
            fi
      - run:
          name: Run project
          command: |
            docker run -d -p 5000:5000 kt2505/my-node-image:latest npm start

workflows:
  version: 2
  build_and_run:
    jobs:
      - run_project
