version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17

    steps:
      - checkout

      # Install Docker
      - setup_remote_docker

      # Build Docker image
      - run:
          name: Build Docker Image
          command: |
            docker build -t your_image_name .

      # Push Docker image to a registry (e.g., Docker Hub)
      - run:
          name: Push Docker Image
          command: |
            echo "Kartik@2505" | docker login -u "kt2505" --password-stdin
            docker tag your_image_name "kt2505/your_image_name"
            docker push "kt2505/your_image_name"

    # Run Docker container
      - run:
          name: Run Docker Container
          command: |
            docker run -d -p 5000:5000 "kt2505/your_image_name"
workflows:
  version: 2
  build:
    jobs:
      - build
