version: 2.1
jobs:
  run_test:
    docker:
      - image: kt2505/my-node-image:latest
    steps:
      - checkout
      - run: 
          name: Install npm dependencies
          command: npm install --save
     - run:
          name: Run project
          command: npm start 

workflows:
  version: 2
  build_and_run:
    jobs:
      - run_project