version: 2.1
jobs:
  run_test:
    docker:
      - image: kt2505/my-node-image:latest
       auth:
          username: kt2505
          password: Kartik@2505
    steps:
      - checkout
      - run: 
          name: Install npm dependencies
          command: npm install --save
    
workflows:
  build_test:
    jobs:
      - run_test
