version: 2.1
jobs:
  first_job:
    docker:
      - image: circleci/node:21

    steps:
      - checkout
      - run:
          name: install library
          command: npm install

workflows:
  version: 2
  build:
    jobs:
      - first_job