version: 2.1
jobs:
  first_job:
   docker:
      - image: circle/node:14.17
   steps:
      - checkout
      - run:
          name: Npm Lib
          command: npm install
  
workflows:
  version: 2
  build:
    jobs:
      - first_job          
