version: 2.1
jobs:
  run_project:
    steps:
      - checkout
      - run:
          name: Build Image
          command: |
            docker build -t test_image .
      - run:
          name: Deploy Image to Registry
          command: |
            docker tag test_image kt2505/test_image:latest
            docker push kt2505/test_image:latest

workflows:
  version: 2
  build_and_run:
    jobs:
      - run_project
