version: 2.1
jobs:
  run_test:
    docker:
      - image: kt2505/my-node-image:latest
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
      - run:
          name: Authenticate to Docker Hub
          command: echo "Kartik@2505" | docker login -u "kt2505" --password-stdin
      - run: 
          name: Install npm dependencies
          command: npm install --save
    
workflows:
  build_test:
    jobs:
      - run_test
