version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17

    steps:
      - checkout

      # Restore cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # Add more cache keys as needed for different dependencies or files

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Save cache
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            # Add more paths as needed for other cached directories

      # Your other build steps go here

workflows:
  version: 2
  build:
    jobs:
      - build
