version: 2.1
jobs:
  run_test:
    docker:
      - image: my-node-image:latest
    steps:
      - checkout
      -run: 
        name: Install npm dependencies
        command: |
          npm install --save
    
workflows:
  build_test:
    jobs:
      - run_test