version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17

    steps:
      - checkout

      # Install Docker
      - setup_remote_docker

      # Build Docker image
      - run:
          name: Build Docker Image
          command: |
            docker build -t test_image .

      # Push Docker image to a registry (e.g., Docker Hub)
      - run:
          name: Push Docker Image
          command: |
            echo "Kartik@2505" | docker login -u "kt2505" --password-stdin
            docker tag test_image "kt2505/test_image"
            docker push "kt2505/test_image"

      # Run Docker container and capture the container ID
      - run:
          name: Run Docker Container
          command: |
            CONTAINER_ID=$(docker run -d -p 5000:5000 "kt2505/test_image")
            echo "Container started with ID: $CONTAINER_ID"
            if docker inspect --format '{{.State.Running}}' $CONTAINER_ID &> /dev/null; then
              echo "Container is already running."
            else
              echo "Container is not running. Starting...$CONTAINER_ID"
              docker start $CONTAINER_ID
            fi

  docker_container_ip:
    docker:
      - image: circleci/node:14.17

    steps:
      - checkout

      # Install Docker
      - setup_remote_docker

      # Output container IP
      - run:
          name: Show Container IP
          command: |
            CONTAINER_IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' $(docker ps -q))
            echo "Server is running at http://$CONTAINER_IP:5000"

workflows:
  version: 2
  build:
    jobs:
      - build
      - docker_container_ip
